# Generated by Django 5.2.12 on 2026-03-08 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Crypto AI', max_length=120)),
                ('meta_title', models.CharField(default='Crypto AI | Real-Time Crypto Market Signal Support', max_length=160)),
                ('meta_description', models.CharField(default='Crypto AI scans market structure in real time, filters weak setups, and helps traders focus on higher-quality crypto entries.', max_length=255)),
                ('badge_text', models.CharField(default='Launch access / $3', max_length=80)),
                ('hero_title', models.CharField(default='Crypto AI finds cleaner setups before emotion takes over.', max_length=180)),
                ('hero_lead', models.TextField(default='Watch the market in real time, filter weak entries, and focus on moves that deserve attention instead of chasing candles.')),
                ('primary_button_text', models.CharField(default='Buy Now', max_length=40)),
                ('primary_button_url', models.URLField(default='https://payhip.com/b/50WXH')),
                ('secondary_button_text', models.CharField(default='See Features', max_length=40)),
                ('hero_card_label', models.CharField(default='Launch package', max_length=60)),
                ('price_text', models.CharField(default='$3', max_length=40)),
                ('price_note', models.CharField(default='one-time launch access', max_length=80)),
                ('hero_card_copy', models.TextField(default='Get access to the launch version now and use it as a decision-support layer before making crypto entries.')),
                ('disclaimer', models.TextField(default='Decision-support software. It does not guarantee profits and should not replace risk management.')),
                ('features_eyebrow', models.CharField(default='Core features', max_length=60)),
                ('features_heading', models.CharField(default='What Crypto AI actually does', max_length=120)),
                ('features_intro', models.TextField(default='Built to reduce emotional entries and turn noisy market behavior into cleaner, more readable decision support.')),
                ('why_eyebrow', models.CharField(default='Why it matters', max_length=60)),
                ('why_heading', models.CharField(default='Most losses start before the trade is even opened.', max_length=120)),
                ('why_copy', models.TextField(default='Traders usually get hurt by timing mistakes, weak conviction, or entering on noise. Crypto AI is built to slow that process down and surface better moments for review.')),
                ('workflow_eyebrow', models.CharField(default='Simple workflow', max_length=60)),
                ('workflow_heading', models.CharField(default='Use it in three clear steps', max_length=120)),
                ('workflow_intro', models.TextField(default='The workflow stays simple so you can move from market scan to action without getting buried in unnecessary complexity.')),
                ('cta_eyebrow', models.CharField(default='Ready to test it', max_length=60)),
                ('cta_heading', models.CharField(default='Get Crypto AI for the $3 launch price.', max_length=120)),
                ('cta_copy', models.TextField(default='Early access is intentionally priced low so you can test the launch version before the future PRO upgrade expands the feature set.')),
                ('cta_button_text', models.CharField(default='Buy on Payhip', max_length=40)),
                ('footer_text', models.CharField(default='Crypto AI is built for market decision support, not guaranteed returns.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing page',
                'verbose_name_plural': 'Landing page',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.landingpagecontent')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('value', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=140)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='main.landingpagecontent')),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProofPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('text', models.CharField(max_length=120)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_points', to='main.landingpagecontent')),
            ],
            options={
                'verbose_name': 'Proof point',
                'verbose_name_plural': 'Proof points',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_reasons', to='main.landingpagecontent')),
            ],
            options={
                'verbose_name': 'Value reason',
                'verbose_name_plural': 'Value reasons',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('number', models.CharField(default='01', max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='main.landingpagecontent')),
            ],
            options={
                'verbose_name': 'Workflow step',
                'verbose_name_plural': 'Workflow steps',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
    ]
