# Generated by Django 5.2.12 on 2026-03-10 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='accounts_copy',
            field=models.TextField(default='Accounts are stored on the server with proper password hashing, staff moderation, and analytics on visits, signups, and checkout clicks.'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='accounts_eyebrow',
            field=models.CharField(default='Real accounts', max_length=60),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='accounts_heading',
            field=models.CharField(default='Register once, keep your access status and release updates in one place.', max_length=120),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq_eyebrow',
            field=models.CharField(default='FAQ', max_length=60),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq_heading',
            field=models.CharField(default='Questions users usually ask before they register or buy.', max_length=120),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq_intro',
            field=models.TextField(default='Short answers to the practical questions that matter before onboarding.'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_eyebrow',
            field=models.CharField(default='Product versions', max_length=60),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_heading',
            field=models.CharField(default='Base version is live now. Pro v2.0 is still in development.', max_length=120),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_intro',
            field=models.TextField(default='The public release is the $3 base build. Pro v2.0 is planned as the next stronger version with broader filters and a cleaner operator workflow.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='badge_text',
            field=models.CharField(default='Base version live / $3 one-time / Pro v2.0 in development', max_length=120),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='cta_button_text',
            field=models.CharField(default='Buy Base Version', max_length=40),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='cta_copy',
            field=models.TextField(default='Use the current base release if you want the working build today. Use your account dashboard to follow access and future Pro updates.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='cta_eyebrow',
            field=models.CharField(default='Ready to move', max_length=60),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='cta_heading',
            field=models.CharField(default='Buy the current base version for $3 and keep the Pro v2.0 roadmap separate.', max_length=120),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='disclaimer',
            field=models.TextField(default='Decision-support software. It does not guarantee profits and should not replace risk management or independent review.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='features_eyebrow',
            field=models.CharField(default='Base version', max_length=60),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='features_heading',
            field=models.CharField(default='What Codevanta Base actually does', max_length=120),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='features_intro',
            field=models.TextField(default='This is the real public build: a focused decision-support layer for cleaner trade review, not a fake all-in-one SaaS promise.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='footer_text',
            field=models.CharField(default='Codevanta is built for market decision support, not guaranteed returns.', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='hero_card_copy',
            field=models.TextField(default='Buy the base build now, keep a real account on the site, and use the dashboard to track access, release status, and Pro v2.0 updates.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='hero_card_label',
            field=models.CharField(default='Current release', max_length=60),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='hero_lead',
            field=models.TextField(default='The current release is a lightweight crypto AI decision-support program with live market scan, weak-setup filtering, setup scoring, and a real account dashboard for access and release tracking.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='hero_title',
            field=models.CharField(default='Codevanta Base is live now. Pro v2.0 is still in development.', max_length=180),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='meta_description',
            field=models.CharField(default='Codevanta Base is the current $3 crypto AI decision-support release. Register a real account, manage access, and follow the Pro v2.0 roadmap.', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='meta_title',
            field=models.CharField(default='Codevanta | Base Crypto AI Program + Real User Access', max_length=160),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='price_note',
            field=models.CharField(default='one-time base version access', max_length=80),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='primary_button_text',
            field=models.CharField(default='Buy Base Version', max_length=40),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='secondary_button_text',
            field=models.CharField(default='Create Account', max_length=40),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='site_name',
            field=models.CharField(default='Codevanta', max_length=120),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='why_copy',
            field=models.TextField(default='Traders usually get hurt by timing mistakes, weak conviction, or entering on noise. Codevanta is built to slow that process down and surface cleaner moments for review.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='why_heading',
            field=models.CharField(default='Most trading damage happens before the order is even opened.', max_length=120),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='workflow_eyebrow',
            field=models.CharField(default='Workflow', max_length=60),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='workflow_heading',
            field=models.CharField(default='Use it in four clear steps', max_length=120),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='workflow_intro',
            field=models.TextField(default='The workflow stays short: scan, score, decide, and review without burying yourself in unnecessary panels.'),
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.CharField(max_length=180)),
                ('answer', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='main.landingpagecontent')),
            ],
            options={
                'verbose_name': 'FAQ item',
                'verbose_name_plural': 'FAQ items',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('badge', models.CharField(blank=True, max_length=120)),
                ('price', models.CharField(max_length=40)),
                ('billing', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('cta_text', models.CharField(default='Open', max_length=40)),
                ('url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('feature_list', models.TextField(blank=True, help_text='One feature per line.')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='main.landingpagecontent')),
            ],
            options={
                'verbose_name': 'Product plan',
                'verbose_name_plural': 'Product plans',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('focus', models.CharField(choices=[('Spot swing', 'Spot swing'), ('Futures momentum', 'Futures momentum'), ('DCA building', 'DCA building'), ('Mixed routine', 'Mixed routine')], default='Mixed routine', max_length=40)),
                ('wants_pro_updates', models.BooleanField(default=True)),
                ('base_purchase_status', models.CharField(choices=[('not_purchased', 'Not purchased'), ('purchased', 'Purchased'), ('granted', 'Granted manually')], default='not_purchased', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('base_checkout', 'Base checkout'), ('pro_waitlist', 'Pro waitlist')], db_index=True, max_length=40)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='main_conver_event_t_d60ab3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(db_index=True, max_length=64)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('referrer', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('utm_content', models.CharField(blank=True, max_length=120)),
                ('utm_term', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'path'], name='main_sitevi_created_b2fe2a_idx'), models.Index(fields=['visitor_key', 'created_at'], name='main_sitevi_visitor_5408b3_idx')],
            },
        ),
    ]
